# Generated by Django 6.0.4 on 2026-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
